### ISSUE TITLE
Updating Causes rendering issues

### ISSUE THREAD

**Issue by Findarato** [livewire/livewire#2557]
### Description
All of my livewire components fail when updating from 2.3.8 to anything higher.  All pages result in 

Too few arguments to function Illuminate\Support\Str::replaceFirst(), 2 passed in /var/www/laraplex8.test/vendor/livewire/livewire/src/helpers.php on line 12 and exactly 3 expected (View: /var/www/laraplex8.test/resources/views/knowledge/index.blade.php)

### Exact steps to reproduce

Updating livewire/livewire to anything higher than 2.3.8.

### Stripped-down, copy-pastable code snippets

```bash
php artisan livewire:discover                                                                                                                                                                              0.93 

   ArgumentCountError

  Too few arguments to function Illuminate\Support\Str::replaceFirst(), 2 passed in /var/www/laraplex8.test/vendor/livewire/livewire/src/helpers.php on line 12 and exactly 3 expected

  at vendor/laravel/framework/src/Illuminate/Support/Str.php:508
    504▕      * @param  string  $replace
    505▕      * @param  string  $subject
    506▕      * @return string
    507▕      */
  ➜ 508▕     public static function replaceFirst($search, $replace, $subject)
    509▕     {
    510▕         if ($search == '') {
    511▕             return $subject;
    512▕         }

      +23 vendor frames
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

Here is one of my components.  
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class FancyCategory extends Component
{
    public $size;
    public $color;
    public $image;
    public $icon = null;
    public $display = null;
    public $path;
    public $extra = "";

    public function render()
    {
        switch ($this->color) {
            case 'blue':
                $this->color = 'bg-blue-800 border-blue-400';
                break;
                break;
            default:
                $this->color = 'bg-gray-800 border-gray-400';
                break;
        }

        switch ($this->size) {
            case 'small':
                $this->image = 'w-4 h-4';
                break;

            case 'medium':
                $this->image = 'w-6 h-6';
                break;

            case 'large':
                $this->image = 'w-10 h-10';
                break;

            default:
                $this->image = 'w-6 h-6';
                break;
        }

        return view('livewire.fancy-category');
    }

    public function go(string $path)
    {
        return redirect($path);
    }
}


```
Just more things that fail when doing

**Context**
- Livewire version: 2.3.8
- Laravel version: 8.19

**Comment by Findarato** [comment]
Closing this as I found my solution 
https://github.com/livewire/livewire/issues/2447

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
